version: 2.1

defaults: &defaults
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: python3 main.py
  test:
    <<: *defaults
    steps:
      - checkout
      - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build