version: 2.1

commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id

defaults: &defaults
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"

jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - run: python3 main.py
      - print_pipeline_id:
          id: << pipeline.id >>
  test:
    <<: *defaults
    steps:
      - checkout
      - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build